from algosdk import account, mnemonic

private_key_a, public_key_a = account.generate_account()
private_key_b, public_key_b = account.generate_account()
private_key_c, public_key_c = account.generate_account()
private_key_d, public_key_d = account.generate_account()
mnemonic_a = mnemonic.from_private_key(private_key_a)
mnemonic_b = mnemonic.from_private_key(private_key_b)
mnemonic_c = mnemonic.from_private_key(private_key_c)
mnemonic_d = mnemonic.from_private_key(private_key_d)

# print(f'main artist public key: {public_key_a}\n')
# print(f'sound artist public key: {public_key_b}\n')
# print(f'buyer 1 public key: {public_key_c}\n')
# print(f'buyer 2 public key: {public_key_d}\n')
#
# print(f'main artist private key: {private_key_a}\n')
# print(f'sound artist private key: {private_key_b}\n')
# print(f'buyer 1 private key: {private_key_c}\n')
# print(f'buyer 2 private key: {private_key_d}\n')
#
# print(f'main artist mnemonic: {mnemonic_a}\n')
# print(f'sound artist mnemonic: {mnemonic_b}\n')
# print(f'buyer 1 mnemonic: {mnemonic_c}\n')
# print(f'buyer 2 mnemonic: {mnemonic_d}\n')

with open('../.env', 'w') as f:
    f.write(f'ARTIST_MAIN_ADDRESS="{public_key_a}"\n')
    f.write(f'ARTIST_MAIN_SECRET="{private_key_a}"\n')
    f.write(f'ARTIST_MAIN_MNEMONIC="{mnemonic_a}"\n')
    f.write(f'ARTIST_SOUND_ADDRESS="{public_key_b}"\n')
    f.write(f'ARTIST_SOUND_SECRET="{private_key_b}"\n')
    f.write(f'ARTIST_SOUND_MNEMONIC="{mnemonic_b}"\n')
    f.write(f'BUYER_1_ADDRESS="{public_key_c}"\n')
    f.write(f'BUYER_1_SECRET="{private_key_c}"\n')
    f.write(f'BUYER_1_MNEMONIC="{mnemonic_c}"\n')
    f.write(f'BUYER_2_ADDRESS="{public_key_d}"\n')
    f.write(f'BUYER_2_SECRET="{private_key_d}"\n')
    f.write(f'BUYER_2_MNEMONIC="{mnemonic_d}"\n')
    f.flush()
